// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dajghtnduzkdpdgglany.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhamdodG5kdXprZHBkZ2dsYW55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MTc3MzksImV4cCI6MjA3MTk5MzczOX0.jJ3k1JAPqUQZO0kthL72NR0_A1RRoqwDmvtpAWgEFtc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});